2021년 10월 9일에 마지막으로 테스트되었습니다.

이 자료는 위키독스 '딥 러닝을 이용한 자연어 처리 입문'의 센텐스피스 튜토리얼 자료입니다.

링크 : https://wikidocs.net/86657

# 1. IMDB 리뷰

In [1]:
pip install sentencepiece

Requirement already satisfied: sentencepiece in /home/affx/pytorch-nlp-tutorial/.venv/lib/python3.12/site-packages (0.2.1)
Note: you may need to restart the kernel to use updated packages.

In [1]:
pip list | grep sentencepiece

sentencepiece             0.2.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
import sentencepiece as spm
import pandas as pd
import urllib.request
import csv

In [4]:
urllib.request.urlretrieve("https://raw.githubusercontent.com/LawrenceDuan/IMDb-Review-Analysis/master/IMDb_Reviews.csv", filename="data/IMDb_Reviews.csv")

('data/IMDb_Reviews.csv', <http.client.HTTPMessage at 0x7dbf0b6ff590>)

In [5]:
train_df = pd.read_csv('data/IMDb_Reviews.csv')
train_df['review']

0        My family and I normally do not watch local mo...
1        Believe it or not, this was at one time the wo...
2        After some internet surfing, I found the "Home...
3        One of the most unheralded great works of anim...
4        It was the Sixties, and anyone with long hair ...
                               ...
49995    the people who came up with this are SICK AND ...
49996    The script is so so laughable... this in turn,...
49997    "So there's this bride, you see, and she gets ...
49998    Your mind will not be satisfied by this nobud...
49999    The chaser's war on everything is a weekly sho...
Name: review, Length: 50000, dtype: object

In [6]:
print('리뷰 개수 :',len(train_df)) # 리뷰 개수 출력

리뷰 개수 : 50000

In [7]:
with open('data/imdb_review.txt', 'w', encoding='utf8') as f:
    f.write('\n'.join(train_df['review']))

In [8]:
spm.SentencePieceTrainer.Train('--input=data/imdb_review.txt --model_prefix=imdb --vocab_size=5000 --model_type=bpe --max_sentence_length=9999')

sentencepiece_trainer.cc(178) LOG(INFO) Running command: --input=data/imdb_review.txt --model_prefix=imdb --vocab_size=5000 --model_type=bpe --max_sentence_length=9999
sentencepiece_trainer.cc(78) LOG(INFO) Starts training with :
trainer_spec {
  input: data/imdb_review.txt
  input_format:
  model_prefix: imdb
  model_type: BPE
  vocab_size: 5000
  self_test_sample_size: 0
  character_coverage: 0.9995
  input_sentence_size: 0
  shuffle_input_sentence: 1
  seed_sentencepiece_size: 1000000
  shrinking_factor: 0.75
  max_sentence_length: 9999
  num_threads: 16
  num_sub_iterations: 2
  max_sentencepiece_length: 16
  split_by_unicode_script: 1
  split_by_number: 1
  split_by_whitespace: 1
  split_digits: 0
  pretokenization_delimiter:
  treat_whitespace_as_suffix: 0
  allow_whitespace_only_pieces: 0
  required_chars:
  byte_fallback: 0
  vocabulary_output_piece_score: 1
  train_extremely_large_corpus: 0
  seed_sentencepieces_file:
  hard_vocab_limit: 1
  use_all_vocab: 0
  unk_id: 0
  bos_id: 1
  eos_id: 2
  pad_id: -1
  unk_piece: <unk>
  bos_piece: <s>
  eos_piece: </s>
  pad_piece: <pad>
  unk_surface:  ⁇
  enable_differential_privacy: 0
  differential_privacy_noise_level: 0
  differential_privacy_clipping_threshold: 0
}
normalizer_spec {
  name: nmt_nfkc
  add_dummy_prefix: 1
  remove_extra_whitespaces: 1
  escape_whitespaces: 1
  normalization_rule_tsv:
}
denormalizer_spec {}
trainer_interface.cc(355) LOG(INFO) SentenceIterator is not specified. Using MultiFileSentenceIterator.
trainer_interface.cc(186) LOG(INFO) Loading corpus: data/imdb_review.txt
trainer_interface.cc(382) LOG(WARNING) Found too long line (10321 > 9999).
trainer_interface.cc(384) LOG(WARNING) Too long lines are skipped in the training.
trainer_interface.cc(385) LOG(WARNING) The maximum length can be changed with --max_sentence_length=<size> flag.
trainer_interface.cc(411) LOG(INFO) Loaded all 49994 sentences
trainer_interface.cc(418) LOG(INFO) Skipped 6 too long sentences.
trainer_interface.cc(427) LOG(INFO) Adding meta_piece: <unk>
trainer_interface.cc(427) LOG(INFO) Adding meta_piece: <s>
trainer_interface.cc(427) LOG(INFO) Adding meta_piece: </s>
trainer_interface.cc(432) LOG(INFO) Normalizing sentences...
trainer_interface.cc(541) LOG(INFO) all chars count=65449658
trainer_interface.cc(552) LOG(INFO) Done: 99.9552% characters are covered.
trainer_interface.cc(562) LOG(INFO) Alphabet size=76
trainer_interface.cc(563) LOG(INFO) Final character coverage=0.999552
trainer_interface.cc(594) LOG(INFO) Done! preprocessed 49994 sentences.
trainer_interface.cc(600) LOG(INFO) Tokenizing input sentences with whitespace: 49994
trainer_interface.cc(611) LOG(INFO) Done! 438648
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=1557312 min_freq=373
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=384101 size=20 all=3611 active=1972 piece=en
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=220588 size=40 all=4932 active=3293 piece=om
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=158358 size=60 all=6355 active=4716 piece=ie
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=106638 size=80 all=7931 active=6292 piece=id
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=90444 size=100 all=9108 active=7469 piece=am
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=90105 min_freq=5590
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=65629 size=120 all=10552 active=2264 piece=ally
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=54599 size=140 all=11902 active=3614 piece=▁have
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=47018 size=160 all=13192 active=4904 piece=▁k
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=41819 size=180 all=14928 active=6640 piece=ol
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=37033 size=200 all=16837 active=8549 piece=ven
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=37018 min_freq=4995
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=34053 size=220 all=18236 active=2327 piece=▁me
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=30398 size=240 all=19803 active=3894 piece=▁un
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=27178 size=260 all=21138 active=5229 piece=▁get
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=24165 size=280 all=21984 active=6075 piece=▁bec
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=22036 size=300 all=22865 active=6956 piece=▁watch
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=22031 min_freq=3786
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=20573 size=320 all=24298 active=2568 piece=▁kn
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=19165 size=340 all=26041 active=4311 piece=▁pe
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=18034 size=360 all=26899 active=5169 piece=▁how
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=16799 size=380 all=27926 active=6196 piece=other
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=15869 size=400 all=29087 active=7357 piece=▁direct
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=15837 min_freq=2654
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=14689 size=420 all=30336 active=2691 piece=▁movies
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=13994 size=440 all=31414 active=3769 piece=ob
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=13210 size=460 all=32677 active=5032 piece=▁plot
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=12444 size=480 all=33129 active=5484 piece=ittle
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=11855 size=500 all=34392 active=6747 piece=ved
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=11779 min_freq=2013
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=11066 size=520 all=35367 active=2659 piece=▁br
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=10278 size=540 all=36441 active=3733 piece=vers
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=9987 size=560 all=37360 active=4652 piece=augh
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=9449 size=580 all=38291 active=5583 piece=ense
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=8980 size=600 all=39016 active=6308 piece=▁performan
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=8915 min_freq=1643
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=8632 size=620 all=39980 active=2913 piece=▁ap
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=8202 size=640 all=40330 active=3263 piece=▁set
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=7865 size=660 all=41238 active=4171 piece=▁few
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=7528 size=680 all=42014 active=4947 piece=▁got
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=7345 size=700 all=42491 active=5424 piece=▁Jo
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=7344 min_freq=1382
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=7043 size=720 all=43424 active=3029 piece=▁effect
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=6745 size=740 all=43985 active=3590 piece=ched
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=6523 size=760 all=44838 active=4443 piece=▁high
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=6354 size=780 all=45455 active=5060 piece=▁give
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=6125 size=800 all=46095 active=5700 piece=▁put
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=6123 min_freq=1214
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=6012 size=820 all=46378 active=2570 piece=oot
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=5812 size=840 all=46847 active=3039 piece=▁cons
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=5653 size=860 all=47420 active=3612 piece=▁expl
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=5434 size=880 all=48074 active=4266 piece=▁help
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=5215 size=900 all=48753 active=4945 piece=oney
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=5199 min_freq=1094
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=5050 size=920 all=49421 active=3072 piece=This
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=4922 size=940 all=50658 active=4309 piece=▁worst
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=4820 size=960 all=50989 active=4640 piece=▁episod
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=4686 size=980 all=51744 active=5395 piece=▁job
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=4568 size=1000 all=52338 active=5989 piece=▁ty
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=4568 min_freq=961
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=4487 size=1020 all=52887 active=3155 piece=ray
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=4390 size=1040 all=53364 active=3632 piece=▁money
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=4303 size=1060 all=54345 active=4613 piece=....
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=4198 size=1080 all=54980 active=5248 piece=▁having
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=4079 size=1100 all=55278 active=5546 piece=not
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=4078 min_freq=872
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=4025 size=1120 all=55901 active=3335 piece=▁American
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=3935 size=1140 all=56651 active=4085 piece=▁invol
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=3813 size=1160 all=57291 active=4725 piece=▁Un
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=3755 size=1180 all=57769 active=5203 piece=▁low
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=3658 size=1200 all=58430 active=5864 piece=ains
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=3650 min_freq=783
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=3573 size=1220 all=59095 active=3539 piece=▁exp
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=3490 size=1240 all=59668 active=4112 piece=▁along
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=3408 size=1260 all=59983 active=4427 piece=▁dra
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=3329 size=1280 all=60633 active=5077 piece=▁exam
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=3280 size=1300 all=61064 active=5508 piece=med
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=3279 min_freq=720
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=3220 size=1320 all=61412 active=3340 piece=▁hero
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=3157 size=1340 all=61960 active=3888 piece=▁instead
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=3045 size=1360 all=62710 active=4638 piece=▁doing
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=3008 size=1380 all=63183 active=5111 piece=reme
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2941 size=1400 all=63669 active=5597 piece=▁cor
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=2937 min_freq=664
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2884 size=1420 all=64126 active=3614 piece=▁develop
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2818 size=1440 all=64656 active=4144 piece=▁stars
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2755 size=1460 all=65242 active=4730 piece=ccess
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2690 size=1480 all=65728 active=5216 piece=▁seemed
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2647 size=1500 all=66048 active=5536 piece=▁several
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=2644 min_freq=619
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2597 size=1520 all=66481 active=3736 piece=▁adm
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2549 size=1540 all=66935 active=4190 piece=▁although
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2491 size=1560 all=67431 active=4686 piece=▁self
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2442 size=1580 all=67862 active=5117 piece=▁Char
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2403 size=1600 all=68268 active=5523 piece=sych
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=2399 min_freq=578
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2370 size=1620 all=68618 active=3739 piece=▁mag
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2327 size=1640 all=69221 active=4342 piece=▁stra
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2294 size=1660 all=69644 active=4765 piece=▁contin
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2260 size=1680 all=69946 active=5067 piece=▁Robert
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2224 size=1700 all=70427 active=5548 piece=▁opp
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=2224 min_freq=544
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2193 size=1720 all=70896 active=3981 piece=▁decent
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2151 size=1740 all=71320 active=4405 piece=ys
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2109 size=1760 all=71900 active=4985 piece=▁tele
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2078 size=1780 all=72384 active=5469 piece=ters
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2047 size=1800 all=72878 active=5963 piece=aves
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=2047 min_freq=509
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2019 size=1820 all=73307 active=4037 piece=▁uni
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1992 size=1840 all=73580 active=4310 piece=rench
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1968 size=1860 all=74252 active=4982 piece=cer
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1941 size=1880 all=75104 active=5834 piece=▁known
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1916 size=1900 all=75692 active=6422 piece=▁highly
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=1915 min_freq=475
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1883 size=1920 all=75841 active=3934 piece=▁yourself
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1862 size=1940 all=76110 active=4203 piece=ubl
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1843 size=1960 all=76576 active=4669 piece=▁writer
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1814 size=1980 all=76919 active=5012 piece=bel
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1798 size=2000 all=77360 active=5453 piece=▁moder
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=1797 min_freq=452
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1780 size=2020 all=77498 active=3996 piece=▁turned
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1748 size=2040 all=77953 active=4451 piece=ald
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1716 size=2060 all=78455 active=4953 piece=lt
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1703 size=2080 all=79062 active=5560 piece=▁among
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1676 size=2100 all=79338 active=5836 piece=EN
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=1676 min_freq=427
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1654 size=2120 all=79631 active=4189 piece=lo
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1624 size=2140 all=80075 active=4633 piece=▁sets
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1602 size=2160 all=80421 active=4979 piece=▁upon
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1581 size=2180 all=80746 active=5304 piece=▁clearly
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1562 size=2200 all=80931 active=5489 piece=▁feature
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=1560 min_freq=409
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1542 size=2220 all=81278 active=4392 piece=▁showing
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1522 size=2240 all=81672 active=4786 piece=ltim
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1504 size=2260 all=82115 active=5229 piece=▁George
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1491 size=2280 all=82571 active=5685 piece=▁easy
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1474 size=2300 all=82834 active=5948 piece=upp
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=1473 min_freq=387
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1450 size=2320 all=83095 active=4348 piece=▁Richard
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1433 size=2340 all=83341 active=4594 piece=▁truth
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1409 size=2360 all=83907 active=5160 piece=lin
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1398 size=2380 all=84329 active=5582 piece=▁city
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1376 size=2400 all=84528 active=5781 piece=▁sens
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=1373 min_freq=370
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1360 size=2420 all=85042 active=4721 piece=▁wait
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1339 size=2440 all=85412 active=5091 piece=▁Peter
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1322 size=2460 all=85768 active=5447 piece=▁utter
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1309 size=2480 all=86027 active=5706 piece=▁lame
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1296 size=2500 all=86374 active=6053 piece=▁Com
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=1296 min_freq=352
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1279 size=2520 all=86796 active=4708 piece=▁monster
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1262 size=2540 all=87211 active=5123 piece=▁perfectly
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1250 size=2560 all=87549 active=5461 piece=▁Par
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1240 size=2580 all=87903 active=5815 piece=▁law
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1227 size=2600 all=88309 active=6221 piece=My
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=1227 min_freq=337
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1214 size=2620 all=88696 active=4789 piece=▁conne
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1202 size=2640 all=89060 active=5153 piece=allow
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1191 size=2660 all=89335 active=5428 piece=▁incredibly
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1179 size=2680 all=89740 active=5833 piece=▁conv
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1165 size=2700 all=90011 active=6104 piece=▁occas
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=1165 min_freq=324
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1152 size=2720 all=90351 active=4838 piece=▁invest
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1140 size=2740 all=90728 active=5215 piece=▁manages
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1122 size=2760 all=91194 active=5681 piece=▁langu
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1109 size=2780 all=91436 active=5923 piece=mist
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1099 size=2800 all=91710 active=6197 piece=▁fighting
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=1096 min_freq=310
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1088 size=2820 all=92153 active=5029 piece=▁outside
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1078 size=2840 all=92542 active=5418 piece=▁30
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1067 size=2860 all=92815 active=5691 piece=▁Other
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1058 size=2880 all=93052 active=5928 piece=IS
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1047 size=2900 all=93391 active=6267 piece=▁former
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=1046 min_freq=297
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1038 size=2920 all=93661 active=4939 piece=▁hardly
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1029 size=2940 all=93886 active=5164 piece=ging
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1020 size=2960 all=94303 active=5581 piece=▁accent
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1008 size=2980 all=94523 active=5801 piece=▁rate
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=999 size=3000 all=94949 active=6227 piece=inger
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=999 min_freq=284

In [9]:
vocab_list = pd.read_csv('models/imdb.vocab', sep='\t', header=None, quoting=csv.QUOTE_NONE)
vocab_list.sample(10)

             0     1
15          ▁f   -12
3690  ▁laughed -3687
1041    ▁super -1038
4169     ament -4166
1371   ▁talent -1368
20         ing   -17
581       ably  -578
3040     ▁soul -3037
4269   ▁Little -4266
112         .<  -109

In [10]:
len(vocab_list)

5000

In [46]:
sp = spm.SentencePieceProcessor()
vocab_file = "models/imdb.model"
sp.load(vocab_file)

True

In [12]:
lines = [
  "I didn't at all think of it this way.",
  "I have waited a long time for someone to film"
]
for line in lines:
  print(line)
  print(sp.encode_as_pieces(line))
  print(sp.encode_as_ids(line))
  print()

I didn't at all think of it this way.
['▁I', '▁didn', "'", 't', '▁at', '▁all', '▁think', '▁of', '▁it', '▁this', '▁way', '.']
[41, 624, 4950, 4926, 139, 170, 378, 30, 58, 73, 413, 4945]

I have waited a long time for someone to film
['▁I', '▁have', '▁wa', 'ited', '▁a', '▁long', '▁time', '▁for', '▁someone', '▁to', '▁film']
[41, 142, 1364, 1121, 4, 668, 285, 93, 1079, 33, 91]

In [13]:
sp.GetPieceSize()

5000

In [14]:
sp.IdToPiece(430)

'▁character'

In [15]:
sp.PieceToId('▁character')

430

In [47]:
sp.DecodeIds([41, 142, 1364, 1121, 4, 668, 285, 93, 1079, 33, 91])

'I have waited a long time for someone to film'

In [19]:
sp.DecodePieces(['▁I', '▁have', '▁wa', 'ited', '▁a', '▁long', '▁time', '▁for', '▁someone', '▁to', '▁film'])

'I have waited a long time for someone to film'

In [20]:
print(sp.encode('I have waited a long time for someone to film', out_type=str))
print(sp.encode('I have waited a long time for someone to film', out_type=int))

['▁I', '▁have', '▁wa', 'ited', '▁a', '▁long', '▁time', '▁for', '▁someone', '▁to', '▁film']
[41, 142, 1364, 1121, 4, 668, 285, 93, 1079, 33, 91]

# 2. 네이버 영화 리뷰

In [21]:
import pandas as pd
import sentencepiece as spm
import urllib.request
import csv

In [22]:
urllib.request.urlretrieve("https://raw.githubusercontent.com/e9t/nsmc/master/ratings.txt", filename="data/ratings.txt")

('data/ratings.txt', <http.client.HTTPMessage at 0x7dbf0aaf8980>)

In [23]:
naver_df = pd.read_table('data/ratings.txt')
naver_df[:5]

         id                                           document  label
0   8112052                                어릴때보고 지금다시봐도 재밌어요ㅋㅋ      1
1   8132799  디자인을 배우는 학생으로, 외국디자이너와 그들이 일군 전통을 통해 발전해가는 문화산...      1
2   4655635               폴리스스토리 시리즈는 1부터 뉴까지 버릴께 하나도 없음.. 최고.      1
3   9251303  와.. 연기가 진짜 개쩔구나.. 지루할거라고 생각했는데 몰입해서 봤다.. 그래 이런...      1
4  10067386                        안개 자욱한 밤하늘에 떠 있는 초승달 같은 영화.      1

In [24]:
print('리뷰 개수 :',len(naver_df)) # 리뷰 개수 출력

리뷰 개수 : 200000

In [25]:
print(naver_df.isnull().values.any())

True

In [26]:
naver_df = naver_df.dropna(how = 'any') # Null 값이 존재하는 행 제거
print(naver_df.isnull().values.any()) # Null 값이 존재하는지 확인

False

In [27]:
print('리뷰 개수 :',len(naver_df)) # 리뷰 개수 출력

리뷰 개수 : 199992

In [29]:
with open('data/naver_review.txt', 'w', encoding='utf8') as f:
    f.write('\n'.join(naver_df['document']))

In [30]:
spm.SentencePieceTrainer.Train('--input=data/naver_review.txt --model_prefix=naver --vocab_size=5000 --model_type=bpe --max_sentence_length=9999')

sentencepiece_trainer.cc(178) LOG(INFO) Running command: --input=data/naver_review.txt --model_prefix=naver --vocab_size=5000 --model_type=bpe --max_sentence_length=9999
sentencepiece_trainer.cc(78) LOG(INFO) Starts training with :
trainer_spec {
  input: data/naver_review.txt
  input_format:
  model_prefix: naver
  model_type: BPE
  vocab_size: 5000
  self_test_sample_size: 0
  character_coverage: 0.9995
  input_sentence_size: 0
  shuffle_input_sentence: 1
  seed_sentencepiece_size: 1000000
  shrinking_factor: 0.75
  max_sentence_length: 9999
  num_threads: 16
  num_sub_iterations: 2
  max_sentencepiece_length: 16
  split_by_unicode_script: 1
  split_by_number: 1
  split_by_whitespace: 1
  split_digits: 0
  pretokenization_delimiter:
  treat_whitespace_as_suffix: 0
  allow_whitespace_only_pieces: 0
  required_chars:
  byte_fallback: 0
  vocabulary_output_piece_score: 1
  train_extremely_large_corpus: 0
  seed_sentencepieces_file:
  hard_vocab_limit: 1
  use_all_vocab: 0
  unk_id: 0
  bos_id: 1
  eos_id: 2
  pad_id: -1
  unk_piece: <unk>
  bos_piece: <s>
  eos_piece: </s>
  pad_piece: <pad>
  unk_surface:  ⁇
  enable_differential_privacy: 0
  differential_privacy_noise_level: 0
  differential_privacy_clipping_threshold: 0
}
normalizer_spec {
  name: nmt_nfkc
  add_dummy_prefix: 1
  remove_extra_whitespaces: 1
  escape_whitespaces: 1
  normalization_rule_tsv:
}
denormalizer_spec {}
trainer_interface.cc(355) LOG(INFO) SentenceIterator is not specified. Using MultiFileSentenceIterator.
trainer_interface.cc(186) LOG(INFO) Loading corpus: data/naver_review.txt
trainer_interface.cc(411) LOG(INFO) Loaded all 199992 sentences
trainer_interface.cc(427) LOG(INFO) Adding meta_piece: <unk>
trainer_interface.cc(427) LOG(INFO) Adding meta_piece: <s>
trainer_interface.cc(427) LOG(INFO) Adding meta_piece: </s>
trainer_interface.cc(432) LOG(INFO) Normalizing sentences...
trainer_interface.cc(541) LOG(INFO) all chars count=7242982
trainer_interface.cc(552) LOG(INFO) Done: 99.9501% characters are covered.
trainer_interface.cc(562) LOG(INFO) Alphabet size=1725
trainer_interface.cc(563) LOG(INFO) Final character coverage=0.999501
trainer_interface.cc(594) LOG(INFO) Done! preprocessed 199992 sentences.
trainer_interface.cc(600) LOG(INFO) Tokenizing input sentences with whitespace: 199992
trainer_interface.cc(611) LOG(INFO) Done! 449380
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=145835 min_freq=100
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=15293 size=20 all=124333 active=11699 piece=▁없
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=11921 size=40 all=129320 active=16686 piece=▁1
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=8425 size=60 all=133224 active=20590 piece=▁생
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=7026 size=80 all=137895 active=25261 piece=▁배
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=5692 size=100 all=141885 active=29251 piece=하게
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=5660 min_freq=83
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=4959 size=120 all=145494 active=10211 piece=▁중
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=4472 size=140 all=148078 active=12795 piece=▁끝
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=3830 size=160 all=150805 active=15522 piece=▁영
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=3596 size=180 all=153693 active=18410 piece=▁좋은
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=3227 size=200 all=156373 active=21090 piece=▁기대
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=3219 min_freq=75
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2983 size=220 all=158712 active=10082 piece=야기
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2772 size=240 all=161819 active=13189 piece=▁현
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2580 size=260 all=164836 active=16206 piece=부터
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2414 size=280 all=168187 active=19557 piece=▁심
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2268 size=300 all=170138 active=21508 piece=▁괜찮
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=2251 min_freq=67
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2087 size=320 all=172399 active=10728 piece=리는
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1941 size=340 all=174678 active=13007 piece=것도
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1856 size=360 all=177272 active=15601 piece=▁표
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1781 size=380 all=179752 active=18081 piece=하기
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1694 size=400 all=182457 active=20786 piece=▁반전
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=1687 min_freq=62
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1642 size=420 all=184396 active=10974 piece=▁얼
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1564 size=440 all=186431 active=13009 piece=▁인간
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1490 size=460 all=188816 active=15394 piece=▁솔직
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1435 size=480 all=190437 active=17015 piece=▁굿
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1376 size=500 all=192599 active=19177 piece=었음
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=1367 min_freq=57
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1313 size=520 all=194430 active=11327 piece=▁파
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1249 size=540 all=196073 active=12970 piece=기도
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1209 size=560 all=198224 active=15121 piece=▁공감
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1176 size=580 all=200718 active=17615 piece=때문에
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1142 size=600 all=203465 active=20362 piece=▁영화에
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=1141 min_freq=53
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1113 size=620 all=205648 active=12333 piece=기는
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1071 size=640 all=208057 active=14742 piece=▁싸
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1044 size=660 all=210144 active=16829 piece=▁조금
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1012 size=680 all=212391 active=19076 piece=하면서
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=980 size=700 all=214450 active=21135 piece=대체
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=979 min_freq=49
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=955 size=720 all=216122 active=12343 piece=▁제작
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=929 size=740 all=217887 active=14108 piece=▁웃기
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=896 size=760 all=218986 active=15207 piece=▁영화라고
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=868 size=780 all=220756 active=16977 piece=▁출연
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=854 size=800 all=222279 active=18500 piece=적이고
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=852 min_freq=47
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=832 size=820 all=223990 active=12684 piece=▁싫
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=821 size=840 all=225215 active=13909 piece=▁무섭
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=798 size=860 all=226603 active=15297 piece=▁ᅲ
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=778 size=880 all=228086 active=16780 piece=▁좋아하는
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=765 size=900 all=229344 active=18038 piece=▁봤던
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=764 min_freq=45
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=749 size=920 all=230783 active=12891 piece=▁킬링
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=731 size=940 all=232105 active=14213 piece=▁지루하고
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=719 size=960 all=233502 active=15610 piece=구만
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=705 size=980 all=234590 active=16698 piece=▁큰
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=686 size=1000 all=235694 active=17802 piece=▁암
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=686 min_freq=43
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=673 size=1020 all=237168 active=13193 piece=보단
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=663 size=1040 all=238688 active=14713 piece=▁지루하다
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=643 size=1060 all=240592 active=16617 piece=▁더빙
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=627 size=1080 all=242021 active=18046 piece=▁한국영화
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=614 size=1100 all=243598 active=19623 piece=▁꽤
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=614 min_freq=41
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=600 size=1120 all=244887 active=13444 piece=말이
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=587 size=1140 all=246112 active=14669 piece=▁감동적이
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=576 size=1160 all=247397 active=15954 piece=▁하지
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=563 size=1180 all=248980 active=17537 piece=▁이쁘
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=552 size=1200 all=250470 active=19027 piece=▁영상미
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=551 min_freq=39
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=541 size=1220 all=252001 active=14016 piece=것을
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=526 size=1240 all=253334 active=15349 piece=▁g
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=516 size=1260 all=254953 active=16968 piece=▁기억이
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=509 size=1280 all=256157 active=18172 piece=▁비디오
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=500 size=1300 all=258087 active=20102 piece=▁한마디
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=499 min_freq=37
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=488 size=1320 all=259296 active=14094 piece=개도
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=478 size=1340 all=260519 active=15317 piece=으면서
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=472 size=1360 all=261763 active=16561 piece=되고
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=468 size=1380 all=263365 active=18163 piece=▁잘봤
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=463 size=1400 all=264654 active=19452 piece=▁전부
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=462 min_freq=36
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=454 size=1420 all=265929 active=14464 piece=▁여배우
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=445 size=1440 all=267347 active=15882 piece=▁중간에
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=436 size=1460 all=268368 active=16903 piece=하자
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=429 size=1480 all=269451 active=17986 piece=▁자기
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=423 size=1500 all=270279 active=18814 piece=▁재밌네요
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=422 min_freq=35
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=416 size=1520 all=271916 active=15137 piece=▁압
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=409 size=1540 all=273252 active=16473 piece=▁감독님
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=400 size=1560 all=274314 active=17535 piece=예요
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=394 size=1580 all=275327 active=18548 piece=▁항상
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=388 size=1600 all=276434 active=19655 piece=리의
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=388 min_freq=34
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=383 size=1620 all=277332 active=14596 piece=▁생각해
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=378 size=1640 all=278365 active=15629 piece=▁빌
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=373 size=1660 all=279763 active=17027 piece=봐서
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=369 size=1680 all=280969 active=18233 piece=▁된다
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=363 size=1700 all=281842 active=19106 piece=▁헤
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=363 min_freq=33
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=357 size=1720 all=283226 active=15431 piece=별로
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=353 size=1740 all=284922 active=17127 piece=▁시절
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=349 size=1760 all=285798 active=18003 piece=▁없네
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=345 size=1780 all=286909 active=19114 piece=▁홍콩
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=339 size=1800 all=288072 active=20277 piece=▁참신
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=339 min_freq=32
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=335 size=1820 all=288980 active=15276 piece=▁뮤
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=331 size=1840 all=290091 active=16387 piece=▁안나
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=328 size=1860 all=291232 active=17528 piece=.......
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=323 size=1880 all=292581 active=18877 piece=▁후반부
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=320 size=1900 all=293584 active=19880 piece=영화로
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=320 min_freq=31
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=315 size=1920 all=294603 active=15542 piece=▁아버지
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=311 size=1940 all=295441 active=16380 piece=▁희망
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=307 size=1960 all=296477 active=17416 piece=실망
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=304 size=1980 all=297674 active=18613 piece=▁흘러
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=301 size=2000 all=298464 active=19403 piece=▁신기
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=301 min_freq=30
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=297 size=2020 all=299604 active=16025 piece=▁나라
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=294 size=2040 all=300795 active=17216 piece=▁노출
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=289 size=2060 all=301609 active=18030 piece=▁즐겁
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=286 size=2080 all=302194 active=18615 piece=세가
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=283 size=2100 all=303204 active=19625 piece=화가
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=283 min_freq=29
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=280 size=2120 all=304368 active=16224 piece=▁부모
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=277 size=2140 all=305383 active=17239 piece=▁그의
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=274 size=2160 all=306711 active=18567 piece=▁같네요
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=269 size=2180 all=307539 active=19395 piece=▁증
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=266 size=2200 all=308189 active=20045 piece=▁스케
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=266 min_freq=28
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=264 size=2220 all=309384 active=16596 piece=▁않을
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=261 size=2240 all=310471 active=17683 piece=▁접
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=259 size=2260 all=311523 active=18735 piece=보이
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=257 size=2280 all=312844 active=20056 piece=좋고
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=254 size=2300 all=313649 active=20861 piece=▁밑에
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=254 min_freq=27
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=252 size=2320 all=314886 active=16900 piece=▁가끔
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=250 size=2340 all=315771 active=17785 piece=▁심리
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=248 size=2360 all=316838 active=18852 piece=▁눈이
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=246 size=2380 all=317720 active=19734 piece=▁카메라
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=242 size=2400 all=318935 active=20949 piece=▁사람을
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=242 min_freq=27
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=239 size=2420 all=319902 active=16906 piece=▁든다
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=237 size=2440 all=320577 active=17581 piece=▁곳
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=235 size=2460 all=321365 active=18369 piece=도없고
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=232 size=2480 all=322109 active=19113 piece=럭저럭
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=230 size=2500 all=322996 active=20000 piece=▁해주
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=230 min_freq=26
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=227 size=2520 all=323690 active=16796 piece=▁꾸
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=225 size=2540 all=324676 active=17782 piece=▁아까워
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=223 size=2560 all=325617 active=18723 piece=▁마라
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=222 size=2580 all=326407 active=19513 piece=▁그럭저럭
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=220 size=2600 all=327120 active=20226 piece=▁평생
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=220 min_freq=25
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=218 size=2620 all=327854 active=17063 piece=▁모자
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=216 size=2640 all=328962 active=18171 piece=▁상처
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=214 size=2660 all=329666 active=18875 piece=기로
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=213 size=2680 all=330544 active=19753 piece=으로서
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=211 size=2700 all=331319 active=20528 piece=▁사랑에
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=211 min_freq=25
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=209 size=2720 all=332039 active=17279 piece=▁고생
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=207 size=2740 all=332965 active=18205 piece=▁나타
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=205 size=2760 all=333629 active=18869 piece=▁썩
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=203 size=2780 all=334478 active=19718 piece=▁엘
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=202 size=2800 all=335748 active=20988 piece=▁형편
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=202 min_freq=24
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=200 size=2820 all=336641 active=17671 piece=20
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=199 size=2840 all=337338 active=18368 piece=▁보시
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=198 size=2860 all=338100 active=19130 piece=▁설레
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=196 size=2880 all=339104 active=20134 piece=친다
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=195 size=2900 all=340061 active=21091 piece=재미없
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=195 min_freq=24
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=194 size=2920 all=341157 active=17969 piece=하시는
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=192 size=2940 all=341817 active=18629 piece=▁건지
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=191 size=2960 all=342787 active=19599 piece=▁봐야할
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=189 size=2980 all=343666 active=20478 piece=구니
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=188 size=3000 all=344404 active=21216 piece=▁지구
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=188 min_freq=23
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=186 size=3020 all=345397 active=18179 piece=▁지금은
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=184 size=3040 all=346221 active=19003 piece=▁동물
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=182 size=3060 all=347000 active=19782 piece=re
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=181 size=3080 all=347990 active=20772 piece=점주
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=180 size=3100 all=348699 active=21481 piece=▁일부
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=180 min_freq=23

In [31]:
vocab_list = pd.read_csv('models/naver.vocab', sep='\t', header=None, quoting=csv.QUOTE_NONE)
vocab_list[:10]

       0  1
0  <unk>  0
1    <s>  0
2   </s>  0
3     ..  0
4     영화 -1
5    ▁영화 -2
6     ▁이 -3
7     ▁아 -4
8    ... -5
9     ᄏᄏ -6

In [32]:
vocab_list.sample(10)

         0     1
2581  ▁있다면 -2578
1998    ▁덕 -1995
333     사람  -330
3480     번 -3477
3367     같 -3364
4238     넌 -4235
58      ▁무   -55
4529     겄 -4526
784   ▁영화로  -781
522     ▁파  -519

In [33]:
len(vocab_list)

5000

In [36]:
sp = spm.SentencePieceProcessor()
vocab_file = "models/naver.model"
sp.load(vocab_file)

True

In [37]:
lines = [
  "뭐 이딴 것도 영화냐.",
  "진짜 최고의 영화입니다 ㅋㅋ",
]
for line in lines:
  print(line)
  print(sp.encode_as_pieces(line))
  print(sp.encode_as_ids(line))
  print()

뭐 이딴 것도 영화냐.
['▁뭐', '▁이딴', '▁것도', '▁영화냐', '.']
[136, 970, 1299, 2593, 3276]

진짜 최고의 영화입니다 ㅋㅋ
['▁진짜', '▁최고의', '▁영화입니다', '▁ᄏᄏ']
[54, 204, 825, 121]

In [38]:
sp.GetPieceSize()

5000

In [39]:
sp.IdToPiece(4)

'영화'

In [40]:
sp.PieceToId('영화')

4

In [44]:
sp.DecodeIds([54, 204, 825, 121])

'진짜 최고의 영화입니다 ᄏᄏ'

In [42]:
sp.DecodePieces(['▁진짜', '▁최고의', '▁영화입니다', '▁ᄏᄏ'])

'진짜 최고의 영화입니다 ᄏᄏ'

In [43]:
print(sp.encode('진짜 최고의 영화입니다 ㅋㅋ', out_type=str))
print(sp.encode('진짜 최고의 영화입니다 ㅋㅋ', out_type=int))

['▁진짜', '▁최고의', '▁영화입니다', '▁ᄏᄏ']
[54, 204, 825, 121]